### ISSUE TITLE
Brain  far or plea for help :)

### ISSUE THREAD

**Issue by supernovae** [sebastianbartmann/VPS-Server-Side-Tag-Manager-Config-with-Nginx#1]
Thanks for pulling this simple process together.  I've launched this on my server and nginx  and the containers seem to start and i see the requests get redirected from my litespeed server to nginx - but they don't seem to be hitting the containers as they get a 404 when i try and test them.

Litespeed -> localhost:8443 (Nginx running here) -> tag containers

seems like nginx is trying to serve from virtual root rather than proxy

when i try and run curl test - nginx logs this - 

172.18.0.1 - - [03/Mar/2022:14:56:57 +0000] "GET /var/www/preview/g/collect?v=2&en=page_view&tid=G-1234&cid=123.456&dl=https%3A%2F%2Fexample.com%2F HTTP/1.1" 404 19 "-" "curl/7.74.0"

and i can't see any way to make sure it correctly hits the preview container that is running - do those suckers log anything?  thanks for any pointers :)

**Comment by sebastianbartmann** [comment]
While I don't understand your setup (got no exp. with litespeed) it seems the issue is somewhere between nginx and the outside world. 
A valid request looks like this in my logfile:
172.18.0.1 - - [03/Mar/2022:15:52:00 +0000] "GET /g/collect?v=2&tid=G-XXX&gtm=XXX&&cid=XXX&en=page_view%2F HTTP/1.1" 200 76 "https://XXX.dev/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"

Maybe a DNS or Cert or Port issue? :D
